{% set name = "boilerpy3" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/boilerpy3-{{ version }}.tar.gz
  sha256: a9fede212f80a36dbc7d4f93e35d8636911cb6b37085a3230557d16ad0f076c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - boilerpy3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jmriebold/BoilerPy3
  summary: Python port of Boilerpipe, for HTML boilerplate removal and text extraction
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - masci
